#!/bin/bash
set -e -x

source $(dirname $0)/version

cd $(dirname $0)/..

if ! command -v kind &> /dev/null; then
  ./scripts/e2e-test-install-deps
fi

if [[ "${GITHUB_ACTIONS:-}" != "true" ]]; then
  build_args+=("BUILDER=default")
fi

TAG=${NGINX_TAG}-e2e make -C images/nginx build "${build_args[@]}"
